### PR TITLE
Add install instructions

### PR DESCRIPTION
**Pull request by hlovdal**
Some older update I noticed I had not created pull request for. The update is only the install section. The env part above only shows up because git cannot automatically figure out branch relations, but I included a commit with that update so that it will be conflict free to merge to master.

### CODE REVIEW

**Comment by hlovdal** [comment]
Actually git will trigger a confllict since the file is modified independently on two different paths, but the content itself is not.

```
$ git co -b frebib frebib/master
Branch frebib set up to track remote branch master from frebib.
Switched to a new branch 'frebib'
$ git merge --no-commit install-instructions.frebib
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
$ git diff
diff --cc README.md
index c62afb8,bc53f27..0000000
--- a/README.md
+++ b/README.md
@@@ -33,6 -33,18 +33,21 @@@ $ su-exec --env i
  uid=123 gid=456 groups=456
  ` ` `
  
++<<<<<<< HEAD
++=======
+ ## Installation
+ 
+ To compile and install run
+ 
+ ```shell
+ make
+ make install
+ ```
+ 
+ which will install under `/usr/local`. To install somewhere else you can use the
+ `PREFIX` variable, like `make install PREFIX=$HOME/software`.
+ 
++>>>>>>> install-instructions.frebib
  ## TTY & parent/child handling
  
  Notice how `su` will make `ps` be a child of a shell while `su-exec`
```

**Comment by hlovdal** [comment]
Come to think of it, the best thing to do is to rebase the branch, that solves everything.

**Comment by frebib** [comment]
Rebasing this commit? https://github.com/hlovdal/su-exec/commit/141240110cc18a376187e00c05bd8f128cacfe21

**Comment by frebib** [comment]
nvm, I've decided to merge instead of rebase. Hopefully it'll cause fewer issues in the long-run

**Pull request merged**
